# Generated by Django 3.2.7 on 2021-11-17 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=30)),
                ('pronouns', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('experience', models.CharField(max_length=10)),
                ('contentWarnings', models.CharField(max_length=100)),
                ('contentAllowed', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AvailablePlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=30)),
                ('pronouns', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('experience', models.CharField(max_length=10)),
                ('contentWarnings', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Homebrew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=30)),
                ('pronouns', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('type', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
