# Generated by Django 3.2.7 on 2021-12-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_availablegame_contentallowed'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiceSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dice_id', models.CharField(max_length=3)),
                ('dice_description', models.CharField(max_length=30)),
                ('dice_rented', models.BooleanField()),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=30)),
                ('pronouns', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('checkout_date', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
            ],
        ),
    ]
