# Generated by Django 3.2.7 on 2021-12-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_diceset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablegame',
            name='contentAllowed',
            field=models.CharField(max_length=32),
        ),
    ]
