# Generated by Django 3.2.7 on 2021-12-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_availablegame_contentallowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homebrew',
            name='type',
            field=models.CharField(max_length=12),
        ),
    ]
